name: Electron Playwright Tests

on:
  push:
    branches:
      - test_ci_linux
  pull_request:
    branches:
      - master

jobs:
  e2e-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] #,  ubuntu-latest, windows-latest]
        node-version: [18.x]

    steps:

      - name: Check out code
        uses: actions/checkout@v3.5.3

      - name: Set up Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

#   Linux

      - name: Install packages (Ubuntu OS)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install libxtst-dev libpng++-dev
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Pull Mattermost Docker image and run the Mattermost server
        if: matrix.os == 'ubuntu-latest'
        run: |
          docker pull mattermost/mattermost-enterprise-edition
          docker run -d -p 8065:8065 mattermost/mattermost-enterprise-edition

          # Add a check to wait for Mattermost server to be responsive
          max_attempts=30
          for i in $(seq $max_attempts); do
            if curl -s http://localhost:8065/api/v4/system/ping | grep -q "Pong"; then
              echo "Mattermost server is up and running."
              break
            else
              echo "Waiting for Mattermost server to be responsive... Attempt $i of $max_attempts"
              sleep 30
            fi
          done

          # If the server is still not responsive, consider it as a failure
          if ! curl -s http://localhost:8065/api/v4/system/ping | grep -q "Pong"; then
            echo "Mattermost server did not start correctly."
            exit 1
          fi
          
      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests (Ubuntu OS)
        if: matrix.os == 'ubuntu-latest'
        run: |
          export DISPLAY=:99
          Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &
          npm run test:e2e || true
          # npm run test:e2e:send-report

#   Windows

      - name: Install packages (Windows OS)
        if: matrix.os == 'windows-latest'
        run: |
          npm install -g windows-build-tools
          npm install -g npm@latest
          npm install -g node-gyp
          npm install -g @electron/rebuild
          node-gyp install

      - name: Rebuild robotjs (Windows OS)
        if: matrix.os == 'windows-latest'
        run: |
          SET CL='/std:c++17'
          npx electron-rebuilds -m ./node_modules/robotjs

      - name: Run Playwright tests (Windows OS)
        if: matrix.os == 'windows-latest'
        run: |
          npm run test:e2e
          npm run test:e2e:send-report

#   Mac OS

      - name: Run Playwright tests (Mac OS)
        if: matrix.os == 'macos-latest'
        run: |
          npm run test:e2e || true
          npm run test:e2e:send-report

      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: mochawesome-report
          path: /home/runner/work/desktop/desktop/mochawesome-report/mochawesome.html

  # e2e-ubuntu:
  #   runs-on: ${{ matrix.os }}

  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest] #,  ubuntu-latest, windows-latest]
  #       node-version: [18.x]

  #   steps:

  #     - name: Check out code
  #       uses: actions/checkout@v3.5.3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3.7.0
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'npm'

  #     - name: Install packages (Linux)
  #       if: matrix.os == 'ubuntu-latest'
  #       run: sudo apt-get install libxtst-dev libpng++-dev

  #     - name: Install packages (Windows)
  #       if: matrix.os == 'windows-latest'
  #       run: |
  #         npm install -g windows-build-tools
  #         npm install -g npm@latest
  #         npm install -g node-gyp
  #         npm install -g @electron/rebuild
  #         node-gyp install

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Rebuild robotjs (Windows)
  #       if: matrix.os == 'windows-latest'
  #       run: |
  #         SET CL='/std:c++17'
  #         npx electron-rebuilds -m ./node_modules/robotjs

  #     - name: Run Playwright tests (Linux)
  #       if: matrix.os == 'ubuntu-latest'
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y xvfb
  #         export DISPLAY=:99
  #         Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &
  #         npm run test:e2e || true
  #         # npm run test:e2e:send-report

  #     - name: Run Playwright tests (Mac OS)
  #       if: matrix.os == 'macos-latest'
  #       run: |
  #         npm run test:e2e
  #         npm run test:e2e:send-report

  #     - name: Run Playwright tests (Windows OS)
  #       if: matrix.os == 'windows-latest'
  #       run: |
  #         npm run test:e2e
  #         npm run test:e2e:send-report

  #     - name: Upload Mochawesome Report
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: mochawesome-report
  #         path: /home/runner/work/desktop/desktop/mochawesome-report/mochawesome.html

  # e2e-windows:
  #   runs-on: ${{ matrix.os }}

  #   strategy:
  #     matrix:
  #       os: [windows-latest] #,  ubuntu-latest, windows-latest]
  #       node-version: [18.x]

  #   steps:

  #     - name: Check out code
  #       uses: actions/checkout@v3.5.3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3.7.0
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'npm'

  #     - name: Install packages (Linux)
  #       if: matrix.os == 'ubuntu-latest'
  #       run: sudo apt-get install libxtst-dev libpng++-dev

  #     - name: Install packages (Windows)
  #       if: matrix.os == 'windows-latest'
  #       run: |
  #         npm install -g windows-build-tools
  #         npm install -g npm@latest
  #         npm install -g node-gyp
  #         npm install -g @electron/rebuild
  #         node-gyp install

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Rebuild robotjs (Windows)
  #       if: matrix.os == 'windows-latest'
  #       run: |
  #         SET CL='/std:c++17'
  #         npx electron-rebuilds -m ./node_modules/robotjs

  #     - name: Run Playwright tests (Linux)
  #       if: matrix.os == 'ubuntu-latest'
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y xvfb
  #         export DISPLAY=:99
  #         Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &
  #         npm run test:e2e
  #         npm run test:e2e:send-report

  #     - name: Run Playwright tests (Mac OS)
  #       if: matrix.os == 'macos-latest'
  #       run: |
  #         npm run test:e2e
  #         npm run test:e2e:send-report

  #     - name: Run Playwright tests (Windows OS)
  #       if: matrix.os == 'windows-latest'
  #       run: |
  #         npm run test:e2e || true
  #         npm run test:e2e:send-report

  #     - name: Upload Mochawesome Report
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: mochawesome-report
  #         path: /home/runner/work/desktop/desktop/mochawesome-report/mochawesome.html
